### ISSUE TITLE
[BUG]: Opening Plex triggers refresh rate change to 165Hz

### ISSUE THREAD

**Issue by Oblivious02** [BartoszCichecki/LenovoLegionToolkit#219]
### Version

2.6.0 B1 and 2.5.0 and older versions

### OS

Windows 10 Latest build

### Device

Legion 5 Pro 16ACH6H

### What's wrong?

When I have my laptop on battery mode and refresh rate set to 75Hz, opening Plex automatically triggers the toolkit to change refresh rate to 165Hz

### How to reproduce the bug?

Open plex

### What is the behavior that you expected?

refresh rate not to change

### Logs

[plex refresh rate log_2022_09_24_13_47_43.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9638826/plex.refresh.rate.log_2022_09_24_13_47_43.txt)

### Do you have Lenovo software installed?

- [ ] Lenovo Vantage is installed
- [ ] Lenovo Hotkeys is installed
- [X] None of the above

### Did you disable any Lenovo software using Lenovo Legion Toolkit?

- [X] Lenovo Vantage
- [X] Lenovo Hotkeys
- [ ] I disabled some things on my own (please write below what you did)

**Comment by BartoszCichecki** [comment]
Looks like an issue that was resolved in later BETA builds. Please check the latest one:

[LenovoLegionToolkitSetup_2.6.0_b4.zip](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9638851/LenovoLegionToolkitSetup_2.6.0_b4.zip)

**Comment by BartoszCichecki** [comment]
BETA builds are also post on the Discord server that is linked in README.

**Comment by Oblivious02** [comment]
> BETA builds are also post on the Discord server that is linked in README.


Unfortunately, it's not fixed. I've opened the plex app, the refresh rate changed to 165Hz, closed it and it returned to 75Hz.
Here's the log file: [plex log 2.txt](https://github.com/BartoszCichecki/LenovoLegionToolkit/files/9638853/plex.log.2.txt)

**Comment by BartoszCichecki** [comment]
So I looked through the last log you sent and yes I can see that refresh rate changes from 75 to 165 and then back to 75, but it is not LLT that does the change.

I can see that you are launching Plex:
```
[24/09/2022 14:10:33] [11] [AbstractWMIListener.cs#82:Handler] Event received. [value=(Started, 23400, Plex.exe), listener=InstanceEventListener]
```

And then shortly after that LLT get's notification from Windows that display configuration has changed:
```
[24/09/2022 14:10:40] [1] [DisplayConfigurationListener.cs#36:SystemEvents_DisplaySettingsChanged] Event received.
```

This indicates that something else on your system changes the refresh rate, not LLT. Plex has a feature for refresh rate matching so maybe that? From the log you sent it is clear that it's not LLT that changed refresh rate for you.
